apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: convention-workload-tolerations
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/language: golang
  name: convention-workload-tolerations
  namespace: jeremy
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
      x95castle1.org/nodeSelector: '{"beta.kubernetes.io/os": "linux"}'
  source:
    git:
      ref:
        branch: main
      url: https://github.com/carto-run/app-golang-kpack