---
apiVersion: v1
kind: Secret
metadata:
  name: reg-cred-convention
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
