#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.name + "-webhook"
spec:
  selector:
    app: #@ data.values.name + "-webhook"
  ports:
    - protocol: TCP
      port: 443
      targetPort: webhook