apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    kctrl.carvel.dev/repository-version: v0.1.0
  creationTimestamp: "2023-09-14T18:55:54Z"
  name: multi-purpose-convention-server-repo.conventions.tanzu.vmware.com
spec:
  fetch:
    imgpkgBundle:
      image: harbor-repo.vmware.com/tanzu_practice/conventions/multi-purpose-convention-server-bundle-repo@sha256:4f6e7bc76bc9fa7d117d9ddc4cc389b97039047e32cc29cf3cc5b802339297fe
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
