apiVersion: conventions.carto.run/v1alpha1
kind: ClusterPodConvention
metadata:
  generation: 1
  name: simple-conventions
spec:
  priority: Normal
  selectorTarget: PodTemplateSpec
  webhook:
    #certificate:
    #  name: simple-webhook-cert
    #  namespace: simple-convention
    clientConfig:
      service:
        name: simple-webhook
        namespace: simple-conventions
        port: 80
