apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: multi-purpose-convention-server.conventions.tanzu.vmware.com.0.15.0
spec:
  refName: multi-purpose-convention-server.conventions.tanzu.vmware.com
  releasedAt: "2023-09-15T21:06:43Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: harbor-repo.vmware.com/tanzu_practice/conventions/multi-purpose-convention-server@sha256:9facd20acf070320f2f0caed869fdb32bc97b16ce561e408382feab2a97e4974
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        annotationPrefix:
          default: example.com
          description: Annotation prefix
          type: string
        kubernetes_distribution:
          default: ""
          description: K8s Distribution - set to openshift if using openshift
          type: string
        kubernetes_version:
          default: ""
          description: K8s Version - used for openshift support / logic
          type: string
        name:
          default: multi-purpose-convention
          description: Name for the convention server
          type: string
        namespace:
          default: multi-purpose-convention
          description: Deployment namespace for the convention server
          type: string
        resources:
          additionalProperties: false
          description: Resource limits and requests
          properties:
            limits:
              additionalProperties: false
              properties:
                cpu:
                  default: 100m
                  description: Limits describes the maximum amount of cpu resources
                    allowed.
                  type: string
                memory:
                  default: 256Mi
                  type: string
              type: object
            requests:
              additionalProperties: false
              properties:
                cpu:
                  default: 100m
                  description: Requests describes the minimum amount of cpu resources
                    required.
                  type: string
                memory:
                  default: 20Mi
                  description: Requests describes the minimum amount of memory resources
                  type: string
              type: object
          type: object
      type: object
  version: 0.15.0
